#!/usr/bin/python
#this program demonstrate to connect to the mysql and run a sql and run the mysql command from mysql prompt via python

import os
import mysql.connector

# Open database connection for testing purpose
db = mysql.connector.connect(user='any', password='yourpass', host='xxxxxx',database='sample')
db.close()

def query_fetchall():
    try:
        conn = mysql.connector.connect(user='any', password='yourpass', host='xxxxx',database='sample')
        cursor = conn.cursor()
        cursor.execute("SELECT version()")
        rows = cursor.fetchall()

        print 'Total Row(s):', cursor.rowcount 
        for row in rows:
            print row 
		
		    o=os.popen('mysql < yoursql.sql')
    except Error as e:
        print e 

    finally:
        cursor.close()
        conn.close()

if __name__ == '__main__':
    query_fetchall()
